config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts, only: [:new, :create]
  get '/home',    to:'pages#home'
  get 'terms',    to:'pages#terms'
  get 'privacy',  to:'pages#privacy'
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
#   Validaciones    
validates :name,    presence: true,
                    uniqueness: true
validates :available, inclusion: { in: [true, false] }                   
end

app/models/contact.rb
class Contact < ApplicationRecord
    # Validadciones
    validates :name,    presence: true
    validates :email,   presence: true,
                        format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :message, presence:  true
end

app/models/feature.rb
class Feature < ApplicationRecord
#   Validaciones    
validates :name,    presence: true,
                    uniqueness: true
validates :available, inclusion: { in: [true, false] }        
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  # def index
  #   @contacts = Contact.all
  # end

  # GET /contacts/1 or /contacts/1.json
  # def show
  # end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  # def edit
  # end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to new_contact_path, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  # def update
  #   respond_to do |format|
  #     if @contact.update(contact_params)
  #       format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
  #       format.json { render :show, status: :ok, location: @contact }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @contact.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /contacts/1 or /contacts/1.json
  # def destroy
  #   @contact.destroy

  #   respond_to do |format|
  #     format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def terms
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, 
    require: true 
    %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, 
    required: true,
    pattern: "^[a-zA-Z0-9.!#$%&`*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$",
    style: "text-transform:lowercase",
    onkeyup: "javascript:this.value=this.value.toLowerCase();"
    %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message, 
    require: true, 
    minlength: 10 
    %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ventas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>